\." Manpage for tidybattery
.TH man 1 "20 May 2015" "" ""
.SH NAME
\fBtidybattery \fP- Lightweight GTK tray battery monitor
\fB
.SH SYNOPSIS
.nf
.fam C
\fBtidybattery &\fP
.fam T
.fi
.SH DESCRIPTION
Lightweight GTK tray battery monitor. The original project by [decayofmind](https://github.com/decayofmind/tidybattery) is a fork of [slimebattery](https://github.com/Enrix835/slimebattery) rewritten in Python.  This project is a fork of that with additions of more levels of icon notification and enabling of clicking on the icon to launch a custom command (like the command for the system power manager).
.SH OPTIONS
\fBtidybattery\fP does not require any options.
.SH CONFIGURATION
Create a config file at ~/.tidybattery, using the template in /usr/share/doc/tidybattery/tidybattery.conf, e.g.,
.TP
.B
\fBcp\fP \fB/usr/share/doc/tidybattery/tidybattery.conf\fP \fB~/.tidybattery\fP
.SH AUTHORS
Carlos Veiga Rodrigues <cvrodrigues@gmail.com>
.SH SEE ALSO
See the online documentation at the \fBtidybattery\fP website.

